# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/zhuduoyu/CPU/CPU.cache/wt [current_project]
set_property parent.project_path C:/Users/zhuduoyu/CPU/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/select_for_WriteData.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/Skip_PC.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/control_unit.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/InstructionRegister.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/extend_unit.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/PC_add_four.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/segment_show.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/RAM.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/ROM.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/select.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/DataRegister.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/select4_1.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/ExtendSa.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/PC.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/ALU.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/RegFile.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/jump_ins.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/select_for_WriteReg.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/show.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/debounce.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/scan.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/MultipleCycleCPU.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/div.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/show_mode.v
  //Mac/Home/Desktop/ECOP-16341002-03/MutipleCycleCPU_apply/MutipleCycleCPU_apply.srcs/sources_1/new/cpu_top_control.v
}
read_xdc C:/Users/zhuduoyu/CPU/CPU.srcs/constrs_1/new/CPU.xdc
set_property used_in_implementation false [get_files C:/Users/zhuduoyu/CPU/CPU.srcs/constrs_1/new/CPU.xdc]

synth_design -top cpu_top_control -part xc7a35tcpg236-1
write_checkpoint -noxdef cpu_top_control.dcp
catch { report_utilization -file cpu_top_control_utilization_synth.rpt -pb cpu_top_control_utilization_synth.pb }
